import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ClipboardList, Trash2, Clock, Calculator, Copy, Timer } from 'lucide-react';
import { Timeline } from './Timeline';
import { GlassCard } from './GlassCard';

export const LogAnalyzer = ({ logInput, setLogInput, stats, showSuccess, showError, currentTimeMinutes }) => {

    const handleCopy = () => {
        const summary = `
🕒 *WorkShift Summary*
------------------
🛫 First In: ${stats.firstInTime}
⌛ Log Result: ${stats.totalOutTime + Math.floor(stats.effectiveWorkTime)}m (In-Out)
🏢 Work (Since 1st In): ${Math.floor(stats.realTimeEffectiveWork / 60)}h ${stats.realTimeEffectiveWork % 60}m
☕ Total Breaks: ${stats.totalOutTime}m
------------------
Generated by WorkShift Calc
        `.trim();
        navigator.clipboard.writeText(summary);
        showSuccess("Summary copied to clipboard!");
    };

    return (
        <GlassCard
            title="Activity Logs"
            icon={ClipboardList}
            subtitle="Paste your attendance entries here"
        >
            <div className="absolute top-6 right-6 flex gap-2">
                <button
                    onClick={() => setLogInput("")}
                    className="p-2.5 rounded-xl bg-slate-900/5 dark:bg-white/5 hover:bg-rose-500/10 hover:text-rose-600 transition-all border border-slate-200 dark:border-white/10"
                    title="Clear Logs"
                >
                    <Trash2 className="w-4 h-4 text-slate-500 dark:text-slate-400 group-hover:text-rose-500" />
                </button>
                <button
                    onClick={handleCopy}
                    className="p-2.5 rounded-xl bg-slate-900/5 dark:bg-white/5 hover:bg-emerald-500/10 hover:text-emerald-600 transition-all border border-slate-200 dark:border-white/10"
                    title="Copy Summary"
                >
                    <Copy className="w-4 h-4 text-slate-500 dark:text-slate-400 group-hover:text-emerald-500" />
                </button>
            </div>

            <div className="mt-6">
                <textarea
                    value={logInput}
                    onChange={(e) => setLogInput(e.target.value)}
                    placeholder="Example:&#10;In 09:00&#10;Out 13:00&#10;In 14:00"
                    className="w-full h-56 p-6 rounded-[2rem] bg-slate-950/5 dark:bg-white/5 border border-slate-200 dark:border-white/5 focus:ring-4 focus:ring-indigo-500/10 focus:border-indigo-500/30 outline-none text-base font-bold transition-all resize-none text-slate-900 dark:text-slate-200 placeholder:text-slate-400 dark:placeholder:text-slate-600 tabular-nums"
                />

                <AnimatePresence>
                    {stats.events.length > 0 && (
                        <motion.div
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: 10 }}
                            className="mt-8"
                        >
                            <Timeline events={stats.events} currentMinutes={currentTimeMinutes} />

                            {/* Analytics Summary */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-8">
                                <div className="p-6 rounded-[2rem] bg-indigo-500/5 border border-indigo-500/20 shadow-sm group hover:bg-indigo-500/10 transition-all cursor-default">
                                    <div className="flex items-center gap-2 mb-2">
                                        <Timer className="w-4 h-4 text-indigo-500 animate-pulse" />
                                        <span className="text-[10px] font-black text-indigo-600 dark:text-indigo-400 uppercase tracking-[0.2em]">Effective Work</span>
                                    </div>
                                    <div className="text-3xl font-black text-slate-900 dark:text-white tabular-nums">
                                        {Math.floor(stats.realTimeEffectiveWork / 60)}<span className="text-lg opacity-40 ml-1 mr-2">h</span>
                                        {stats.realTimeEffectiveWork % 60}<span className="text-lg opacity-40 ml-1">m</span>
                                    </div>
                                    <p className="text-[9px] text-slate-500 font-black mt-2 uppercase italic tracking-wider opacity-60">Real-time tracker • Active now</p>
                                </div>

                                <div className="p-6 rounded-[2rem] bg-slate-900/5 dark:bg-white/5 border border-slate-200 dark:border-white/10 group hover:bg-slate-900/10 dark:hover:bg-white/10 transition-all cursor-default">
                                    <div className="flex items-center gap-2 mb-2">
                                        <Calculator className="w-4 h-4 text-slate-400" />
                                        <span className="text-[10px] font-black text-slate-500 dark:text-slate-400 uppercase tracking-[0.2em]">Log Result</span>
                                    </div>
                                    <div className="text-3xl font-black text-slate-900 dark:text-white tabular-nums">
                                        {Math.floor(stats.effectiveWorkTime / 60)}<span className="text-lg opacity-40 ml-1 mr-2">h</span>
                                        {Math.floor(stats.effectiveWorkTime % 60)}<span className="text-lg opacity-40 ml-1">m</span>
                                    </div>
                                    <p className="text-[9px] text-slate-500 font-black mt-2 uppercase italic tracking-wider opacity-60">Static log total • Excludes breaks</p>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </GlassCard>
    );
};
